spring:
  datasource:
#    hikari:
      url: jdbc:mysql://localhost:3306/my_blog?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
